[package]
name = "nbody"
version = "0.1.0"
authors = ["Robin Kruppe <robin.kruppe@gmail.com>"]

[dependencies]
nyuzi_support = { path = "../_rust_support" }

[build-dependencies]
cgmath = "0.14.1"
rand = "0.3.15"
