[package]
name = "_rust_aggregate"
version = "0.1.0"
authors = ["Robin Kruppe <robin.kruppe@gmail.com>"]

[lib]
crate-type = ["staticlib"]

[profile.release]
lto = true

[dependencies]
fib = { path = "../fib" }
nbody = { path = "../nbody" }
fwt = { path = "../fwt" }
